name: CD Selphid, update framewoks, pods and publish

on:
  push:
    tags:
      - '**'
      - '!**-SNAPSHOT'
      - '!**-snapshot'
      - '!**/**-snapshot'
      - '!**-**-snapshot'

# defaults:
#   run:
#     working-directory: ./scripts

jobs:
  deploy_pod_Memb:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail 
        pod trunk push MembSdkiOS.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}